document.addEventListener('DOMContentLoaded', () => {
    const galleryGrid = document.getElementById('gallery-grid');
    const categorizedView = document.getElementById('categorized-view');
    const layoutToggle = document.getElementById('layout-toggle');
    const labelMixed = document.getElementById('label-mixed');
    const labelCategorized = document.getElementById('label-categorized');

    const lightbox = document.getElementById('lightbox');
    const lightboxImg = document.getElementById('lightbox-img');
    const lightboxClose = document.querySelector('.lightbox-close');

    // CONFIGURATION
    const CLOUD_NAME = 'daxgt0qfj';
    let globalResources = []; // Store fetched data

    // Function to load images from static JSON data (generated by GitHub Actions)
    async function loadGallery() {
        try {
            // Show loading state
            galleryGrid.innerHTML = '<div class="loading-state">Loading gallery...</div>';

            // Fetch from the static data file generated by the build script
            const response = await fetch('data/street.json');

            if (!response.ok) {
                // Fallback for initial run before first build
                if (response.status === 404) {
                    throw new Error('Gallery data not found. Please wait for the auto-update to complete.');
                }
                throw new Error(`Data error: ${response.status}`);
            }

            const resources = await response.json();
            globalResources = resources; // Save for toggle switching

            // Initial render based on toggle state
            if (layoutToggle.checked) {
                renderCategorized(globalResources);
            } else {
                renderGallery(globalResources);
            }

        } catch (error) {
            console.error('Gallery Load Error:', error);

            galleryGrid.innerHTML = `
                <div class="error-state">
                    <p>Unable to load gallery.</p>
                    <small style="color:var(--text-secondary)">
                        ${error.message}
                    </small>
                </div>
            `;
        }
    }

    // Render Images
    function renderGallery(resources) {
        galleryGrid.innerHTML = ''; // Clear loading state

        if (!resources || resources.length === 0) {
            galleryGrid.innerHTML = '<div class="loading-state">No street photos found in folder.</div>';
            return;
        }

        resources.forEach((res, index) => {
            // Construct URL using Cloudinary URL conventions
            // Format: https://res.cloudinary.com/<cloud_name>/image/upload/<transformations>/<public_id>.<format>

            // Thumbnail: Small, Compressed
            const imageUrl = `https://res.cloudinary.com/${CLOUD_NAME}/image/upload/q_auto,f_auto,w_800/${res.public_id}.${res.format}`;

            // Full View: High Quality
            const fullUrl = `https://res.cloudinary.com/${CLOUD_NAME}/image/upload/q_auto,f_auto/${res.public_id}.${res.format}`;

            const item = document.createElement('div');
            item.className = 'gallery-item';
            // Stagger animation
            item.style.animationDelay = `${index * 50}ms`;

            const img = document.createElement('img');
            img.className = 'gallery-img';
            img.src = imageUrl;
            img.alt = 'Portrait';
            img.loading = 'lazy';

            // Lightbox Click
            item.addEventListener('click', () => {
                openLightbox(fullUrl);
            });

            item.appendChild(img);
            galleryGrid.appendChild(item);
        });
    }

    // Render Categorized View (Netflix Style)
    function renderCategorized(resources) {
        categorizedView.innerHTML = ''; // Clear existing

        if (!resources || resources.length === 0) {
            categorizedView.innerHTML = '<div class="loading-state">No street photos found in folder.</div>';
            return;
        }

        // Group resources by tag
        // Since tags might not exist yet, we'll create a default "Uncategorized" group
        // If a photo has multiple tags, we'll add it to the first tag's row for simplicity.
        const groups = {};

        // Define some expected mock categories for demonstration if tags are empty
        // In real usage, this will dynamically create rows based on actual Cloudinary tags
        const dummyTags = ['Architecture', 'People', 'Night', 'Cityscapes', 'Black & White'];

        resources.forEach((res, index) => {
            let assignedTag = 'Uncategorized';

            if (res.tags && res.tags.length > 0) {
                // Use the first tag from Cloudinary
                assignedTag = res.tags[0];
            } else {
                // Mock assignment for demonstration based on index if no tags exist
                assignedTag = dummyTags[index % dummyTags.length];
            }

            // Capitalize first letter of tag
            assignedTag = assignedTag.charAt(0).toUpperCase() + assignedTag.slice(1);

            if (!groups[assignedTag]) {
                groups[assignedTag] = [];
            }
            groups[assignedTag].push(res);
        });

        // Build HTML for each group
        Object.keys(groups).sort().forEach(tag => {
            const groupImages = groups[tag];

            const rowDiv = document.createElement('div');
            rowDiv.className = 'cat-row';

            const headerDiv = document.createElement('div');
            headerDiv.className = 'cat-header';
            headerDiv.textContent = tag;
            rowDiv.appendChild(headerDiv);

            const scrollContainer = document.createElement('div');
            scrollContainer.className = 'cat-scroll';

            groupImages.forEach(res => {
                const imageUrl = `https://res.cloudinary.com/${CLOUD_NAME}/image/upload/q_auto,f_auto,w_800/${res.public_id}.${res.format}`;
                const fullUrl = `https://res.cloudinary.com/${CLOUD_NAME}/image/upload/q_auto,f_auto/${res.public_id}.${res.format}`;

                const card = document.createElement('div');
                card.className = 'cat-card';

                const img = document.createElement('img');
                img.src = imageUrl;
                img.loading = 'lazy';
                img.alt = tag + ' Portrait';

                card.addEventListener('click', () => openLightbox(fullUrl));

                card.appendChild(img);
                scrollContainer.appendChild(card);
            });

            rowDiv.appendChild(scrollContainer);
            categorizedView.appendChild(rowDiv);
        });
    }

    // Toggle Listener
    layoutToggle.addEventListener('change', (e) => {
        if (e.target.checked) {
            // Switch to Categorized View
            labelMixed.classList.remove('active');
            labelCategorized.classList.add('active');
            galleryGrid.style.display = 'none';
            categorizedView.style.display = 'block';

            // Only re-render if it's empty to save performance
            if (categorizedView.children.length === 0 && globalResources.length > 0) {
                renderCategorized(globalResources);
            }
        } else {
            // Switch to Mixed View
            labelCategorized.classList.remove('active');
            labelMixed.classList.add('active');
            categorizedView.style.display = 'none';
            galleryGrid.style.display = 'block'; // Ensure masonry columns layout resets
        }
    });

    // Lightbox Logic
    function openLightbox(url) {
        lightboxImg.src = url;
        lightbox.classList.add('active');
        document.body.style.overflow = 'hidden'; // Prevent scrolling
    }

    function closeLightbox() {
        lightbox.classList.remove('active');
        setTimeout(() => {
            lightboxImg.src = '';
        }, 300);
        document.body.style.overflow = '';
    }

    lightboxClose.addEventListener('click', closeLightbox);

    // Close on background click
    lightbox.addEventListener('click', (e) => {
        if (e.target === lightbox) {
            closeLightbox();
        }
    });

    // Close on Escape key
    document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape' && lightbox.classList.contains('active')) {
            closeLightbox();
        }
    });

    // Initialize
    loadGallery();
});
